[package]
name = "serde_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_logger_derive = { "path" = "derive/" }
