[package]
name = "serde_logger_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.94", features = ["full"] }